### PR TITLE
self element in on:bind

### PR DESCRIPTION
**Pull request by hhzl**

### CODE REVIEW

**Comment by herby** [comment]
Squash those commits, please.

**Comment by hhzl** [comment]
Could you please do it?

This happened for me

To https://github.com/hhzl/domite.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/hhzl/domite.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by herby** [comment]
Well, isn't it the right time to invest a few minutes to learn some git-fu? For the first, if you do some feature which you want to put into PR, you should do in the branch of its own (so this does not happen). Second, learn to use 'git rebase -i HEAD~n' as a way to reorganize local history's last n commits.

Close the PR, I'll fix the on:bind: and off:unbind:. You should nevertheless rebase your code later on the upstream/master, anyway. Without it there would be conflicts: `git fetch upstream && git rebase upstream/master`. I presume you have remote 'upstream' created to the main repo so you can do that.

Hannes Hirzel wrote:
> Could you please do it?
>
> This happened for me
>
> To https://github.com/hhzl/domite.git
> ! [rejected] master -> master (non-fast-forward)
> error: failed to push some refs to 'https://github.com/hhzl/domite.git'
> hint: Updates were rejected because the tip of your current branch is 
> behind
> hint: its remote counterpart. Integrate the remote c
hanges (e.g.

**Comment by hhzl** [comment]
Thank you 

I did

    git fetch upstream && git rebase upstream/master
    remote: Counting objects: 7, done.
    remote: Compressing objects: 100% (3/3), done.
    remote: Total 7 (delta 4), reused 7 (delta 4), pack-reused 0
    Unpacking objects: 100% (7/7), done.
    From https://github.com/amber-smalltalk/domite
       b623854..d5d52e9  master     -> upstream/master
      * [new tag]         0.2.4      -> 0.2.4
    First, rewinding head to replay your work on top of it...
    Applying: self element in on:bind
    Using index info to reconstruct a base tree...
    M	    src/DOMite.st
    Falling back to patching base and 3-way merge...
    No changes -- Patch already applied.

**Comment by herby** [comment]
But still did not do `git push -f` I presume, as network graph still shows old things.

**Pull request closed without merging**
